version: "3.9"

services:
  nserver1:
    build:
      context: ./server
    container_name: nserver1
    networks:
      - nginx_network
    expose:
      - "3000"
  nserver2:
    build:
      context: ./server
    container_name: "nserver2"
    networks: 
      - nginx_network
    expose:
      - "3000"
  nginxLB:
    image: nginx:stable
    container_name: "nginxLB"
    networks:
      - nginx_network
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nserver1
      - nserver2
networks:
  nginx_network:
    driver: bridge